
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


['Ftr_ID', 'Ftr_Name', 'Other_Name', 'Last_Updt', 'Ftr_Group', 'Ftr_Type', 'Commodity', 'Pt_Def', 'Poly_Def', 'State', 'County', 'Loc_Scale', 'Loc_Date', 'Ref_Detail', 'Ref_ID', 'Remarks', 'Loc_Poly']
['Ftr_ID', 'Ftr_Name', 'Other_Name', 'Last_Updt', 'Ftr_Group', 'Ftr_Type', 'Commodity', 'Pt_Def', 'Poly_Def', 'State', 'County', 'Loc_Scale', 'Loc_Date', 'Ref_Detail', 'Ref_ID', 'Remarks', 'Loc_Poly']
Traceback (most recent call last):
  File "full_document_ver.py", line 6, in <module>
    path_dir = '/home/yaoyi/pyo00005/CriticalMAAS/src/umn-ta2-mineral-site-linkage/document_testing'
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/polars/dataframe/frame.py", line 6239, in map_rows
    out, is_df = self._df.map_rows(function, return_dtype, inference_size)
  File "full_document_ver.py", line 9, in <lambda>
    pl.struct(pl.all()).alias('data_as_struct')
  File "/panfs/jay/groups/28/yaoyi/pyo00005/CriticalMAAS/src/umn-ta2-mineral-site-linkage/make_output.py", line 156, in create_document
    txt_embed = model.encode(document)
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 153, in encode
    self.to(device)
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "full_document_ver.py", line 8, in <module>
    df_refined_MRDS = df_MRDS.select(
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/polars/dataframe/frame.py", line 6239, in map_rows
    out, is_df = self._df.map_rows(function, return_dtype, inference_size)
  File "full_document_ver.py", line 11, in <lambda>
    lambda x: (create_document(x, dict_MRDS))
  File "/panfs/jay/groups/28/yaoyi/pyo00005/CriticalMAAS/src/umn-ta2-mineral-site-linkage/make_output.py", line 156, in create_document
    txt_embed = model.encode(document)
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 153, in encode
    self.to(device)
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/yaoyi/pyo00005/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
