Traceback (most recent call last):
  File "/common/software/install/migrated/anaconda/python3-2020.07-mamba/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/common/software/install/migrated/anaconda/python3-2020.07-mamba/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/panfs/jay/groups/28/yaoyi/pyo00005/CriticalMAAS/src/umn-ta2-mineral-site-linkage/minelink/__main__.py", line 56, in <module>
    main(parser.parse_args())
  File "/panfs/jay/groups/28/yaoyi/pyo00005/CriticalMAAS/src/umn-ta2-mineral-site-linkage/minelink/__main__.py", line 24, in main
    intralink(list_code, args.use_location_base)
  File "/panfs/jay/groups/28/yaoyi/pyo00005/CriticalMAAS/src/umn-ta2-mineral-site-linkage/minelink/m2_intralinking/intralink.py", line 12, in intralink
    pl_loc_linked = location_based_linking(i, bool_location)
  File "/panfs/jay/groups/28/yaoyi/pyo00005/CriticalMAAS/src/umn-ta2-mineral-site-linkage/minelink/m2_intralinking/location_based.py", line 9, in location_based_linking
    pl_geom = load_file([PATH_TMP_DIR, alias_code],
  File "/panfs/jay/groups/28/yaoyi/pyo00005/CriticalMAAS/src/umn-ta2-mineral-site-linkage/minelink/m0_load_input/load_data.py", line 27, in load_file
    with open(os.path.join(file_path, file_name+'.pkl'), 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: './temporary/ac/df_geometry.pkl'
